// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbiy26KTVjqiNFNDa3hWyQEtUb4j7x1TY',
    appId: '1:994016185147:web:e592b7e5f100a917ebc51e',
    messagingSenderId: '994016185147',
    projectId: 'comhephzisofttodoapp',
    authDomain: 'comhephzisofttodoapp.firebaseapp.com',
    storageBucket: 'comhephzisofttodoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvNNJs568vjvlO1Ky9mJPQwciUoLUbBi8',
    appId: '1:994016185147:android:20006d94a3c7cfb6ebc51e',
    messagingSenderId: '994016185147',
    projectId: 'comhephzisofttodoapp',
    storageBucket: 'comhephzisofttodoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFTIHfdc-lPmp2McssDJ8MmQOAuoOeKkc',
    appId: '1:994016185147:ios:3923009b6254e55debc51e',
    messagingSenderId: '994016185147',
    projectId: 'comhephzisofttodoapp',
    storageBucket: 'comhephzisofttodoapp.appspot.com',
    iosClientId: '994016185147-f42s74okels5b1lu7uh3g8d2n9mk4mak.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );
}
